<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="Menghan Yuan" />


<title>Binary Choice Model</title>

<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.13.2/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/pagedtable-1.1/css/pagedtable.css" rel="stylesheet" />
<script src="site_libs/pagedtable-1.1/js/pagedtable.js"></script>
<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>






<link rel="stylesheet" href="style.css" type="text/css" />



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Course Website</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Binary Choice Model</h1>
<h4 class="author">Menghan Yuan</h4>
<h4 class="date">Oct 25, 2024</h4>

</div>


<SCRIPT language="JavaScript" SRC="my_jxscript.js"></SCRIPT>
<p><a class="top-link" href="#top" id="js-top">↑</a></p>
<p>A limited dependent variable (LDV) <span class="math inline">\(y\)</span> takes values in some “limited” set. Examples:</p>
<ul>
<li>Binary: <span class="math inline">\(y\in \{0,1\}\)</span></li>
<li>Integer: <span class="math inline">\(y\in \{0,1,2, \ldots\}\)</span></li>
<li>Censored: <span class="math inline">\(y\in \mathbb R^+\)</span></li>
</ul>
<p>We will focus on the binary dependent variable case for our course.</p>
<div id="introductory-example" class="section level1">
<h1>Introductory Example</h1>
<p>The western collaborative group study (WCGS) was a large epidemiological study designed to investigate the risk factors and coronary heart disease (CHD).
More than 3000 men were recruited to the study, and a number of (potential) risk factors were recorded at entry. The men were then followed for about ten years and it was recorded if they developed CHD or not.</p>
<p>In this introductory example, we will study <strong>the effect of smoking and age on the risk for CHD</strong>.</p>
<pre class="r"><code>wcgs &lt;- read.table(&quot;https://raw.githubusercontent.com/my1396/course_dataset/refs/heads/main/wcgs.txt&quot;, sep=&quot;\t&quot;, header=TRUE, na.strings=&quot;.&quot;)
wcgs %&gt;% head(20)</code></pre>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":[""],"name":["_rn_"],"type":[""],"align":["left"]},{"label":["id"],"name":[1],"type":["int"],"align":["right"]},{"label":["age"],"name":[2],"type":["int"],"align":["right"]},{"label":["height"],"name":[3],"type":["int"],"align":["right"]},{"label":["weight"],"name":[4],"type":["int"],"align":["right"]},{"label":["sbp"],"name":[5],"type":["int"],"align":["right"]},{"label":["dbp"],"name":[6],"type":["int"],"align":["right"]},{"label":["chol"],"name":[7],"type":["int"],"align":["right"]},{"label":["behpat"],"name":[8],"type":["int"],"align":["right"]},{"label":["ncigs"],"name":[9],"type":["int"],"align":["right"]},{"label":["dibpat"],"name":[10],"type":["int"],"align":["right"]},{"label":["chd69"],"name":[11],"type":["int"],"align":["right"]},{"label":["typchd69"],"name":[12],"type":["int"],"align":["right"]},{"label":["time169"],"name":[13],"type":["int"],"align":["right"]},{"label":["arcus"],"name":[14],"type":["int"],"align":["right"]},{"label":["sbp133"],"name":[15],"type":["int"],"align":["right"]},{"label":["sbp125"],"name":[16],"type":["int"],"align":["right"]},{"label":["sbp125p"],"name":[17],"type":["int"],"align":["right"]},{"label":["uni"],"name":[18],"type":["dbl"],"align":["right"]},{"label":["z1"],"name":[19],"type":["dbl"],"align":["right"]},{"label":["z2"],"name":[20],"type":["dbl"],"align":["right"]},{"label":["t1"],"name":[21],"type":["dbl"],"align":["right"]},{"label":["lnsbp"],"name":[22],"type":["dbl"],"align":["right"]},{"label":["lnwght"],"name":[23],"type":["dbl"],"align":["right"]},{"label":["lnlnsbp"],"name":[24],"type":["dbl"],"align":["right"]},{"label":["invspb"],"name":[25],"type":["dbl"],"align":["right"]},{"label":["iqsbp"],"name":[26],"type":["dbl"],"align":["right"]},{"label":["wghtcat"],"name":[27],"type":["int"],"align":["right"]},{"label":["agec"],"name":[28],"type":["int"],"align":["right"]},{"label":["cholc"],"name":[29],"type":["int"],"align":["right"]},{"label":["smoke"],"name":[30],"type":["int"],"align":["right"]},{"label":["bmi"],"name":[31],"type":["dbl"],"align":["right"]},{"label":["bage_50"],"name":[32],"type":["int"],"align":["right"]},{"label":["chol_50"],"name":[33],"type":["dbl"],"align":["right"]},{"label":["age_10"],"name":[34],"type":["dbl"],"align":["right"]},{"label":["bmi_10"],"name":[35],"type":["dbl"],"align":["right"]},{"label":["sbp_50"],"name":[36],"type":["dbl"],"align":["right"]}],"data":[{"1":"2343","2":"50","3":"67","4":"200","5":"132","6":"90","7":"249","8":"1","9":"25","10":"1","11":"0","12":"0","13":"1367","14":"1","15":"1","16":"0","17":"0","18":"0.4861","19":"-0.5854","20":"0.3584","21":"-1.6334","22":"4.8828","23":"5.2983","24":"1.5857","25":"0.0076","26":"0.0870","27":"200","28":"2","29":"2","30":"1","31":"31.3210","32":"1","33":"0.4526","34":"0.3721","35":"0.6803","36":"0.0673","_rn_":"1"},{"1":"3656","2":"51","3":"73","4":"192","5":"120","6":"74","7":"194","8":"1","9":"25","10":"1","11":"0","12":"0","13":"2991","14":"0","15":"1","16":"1","17":"1","18":"0.1860","19":"-1.5060","20":"0.3706","21":"-4.0634","22":"4.7875","23":"5.2575","24":"1.5660","25":"0.0083","26":"0.0913","27":"200","28":"3","29":"1","30":"1","31":"25.3286","32":"1","33":"-0.6474","34":"0.4721","35":"0.0810","36":"-0.1727","_rn_":"2"},{"1":"3526","2":"59","3":"70","4":"200","5":"158","6":"94","7":"258","8":"1","9":"0","10":"1","11":"0","12":"0","13":"2960","14":"1","15":"0","16":"0","17":"0","18":"0.7278","19":"0.8786","20":"1.3733","21":"0.6397","22":"5.0626","23":"5.2983","24":"1.6219","25":"0.0063","26":"0.0796","27":"200","28":"4","29":"3","30":"0","31":"28.6939","32":"1","33":"0.6326","34":"1.2721","35":"0.4176","36":"0.5873","_rn_":"3"},{"1":"22057","2":"51","3":"69","4":"150","5":"126","6":"80","7":"173","8":"1","9":"0","10":"1","11":"0","12":"0","13":"3069","14":"1","15":"1","16":"0","17":"0","18":"0.6245","19":"0.9651","20":"0.8604","21":"1.1218","22":"4.8363","23":"5.0106","24":"1.5761","25":"0.0079","26":"0.0891","27":"170","28":"3","29":"1","30":"0","31":"22.1487","32":"1","33":"-1.0674","34":"0.4721","35":"-0.2370","36":"-0.0527","_rn_":"4"},{"1":"12927","2":"44","3":"71","4":"160","5":"126","6":"80","7":"214","8":"1","9":"0","10":"1","11":"0","12":"0","13":"3081","14":"0","15":"1","16":"0","17":"0","18":"0.3790","19":"0.6538","20":"-0.2696","21":"2.4250","22":"4.8363","23":"5.0752","24":"1.5761","25":"0.0079","26":"0.0891","27":"170","28":"1","29":"2","30":"0","31":"22.3130","32":"0","33":"-0.2474","34":"-0.2279","35":"-0.2205","36":"-0.0527","_rn_":"5"},{"1":"16029","2":"47","3":"64","4":"158","5":"116","6":"76","7":"206","8":"1","9":"80","10":"1","11":"0","12":"0","13":"2114","14":"0","15":"1","16":"1","17":"1","18":"0.7355","19":"-1.6677","20":"-2.1177","21":"-0.7875","22":"4.7536","23":"5.0626","24":"1.5589","25":"0.0086","26":"0.0928","27":"170","28":"2","29":"2","30":"1","31":"27.1177","32":"0","33":"-0.4074","34":"0.0721","35":"0.2599","36":"-0.2527","_rn_":"6"},{"1":"3894","2":"40","3":"70","4":"162","5":"122","6":"78","7":"190","8":"1","9":"0","10":"1","11":"0","12":"0","13":"2929","14":"0","15":"1","16":"1","17":"1","18":"0.0405","19":"-0.2081","20":"-0.3448","21":"-0.6035","22":"4.8040","23":"5.0876","24":"1.5695","25":"0.0082","26":"0.0905","27":"170","28":"0","29":"1","30":"0","31":"23.2420","32":"0","33":"-0.7274","34":"-0.6279","35":"-0.1276","36":"-0.1327","_rn_":"7"},{"1":"11389","2":"41","3":"70","4":"160","5":"130","6":"84","7":"212","8":"1","9":"25","10":"1","11":"0","12":"0","13":"3010","14":"0","15":"1","16":"0","17":"0","18":"0.3197","19":"0.2288","20":"-0.3990","21":"0.5734","22":"4.8675","23":"5.0752","24":"1.5826","25":"0.0077","26":"0.0877","27":"170","28":"1","29":"2","30":"1","31":"22.9551","32":"0","33":"-0.2874","34":"-0.5279","35":"-0.1563","36":"0.0273","_rn_":"8"},{"1":"12681","2":"50","3":"71","4":"195","5":"112","6":"70","7":"130","8":"1","9":"0","10":"1","11":"0","12":"0","13":"3104","14":"1","15":"1","16":"1","17":"1","18":"0.1886","19":"2.9056","20":"0.1192","21":"24.3710","22":"4.7185","23":"5.2730","24":"1.5515","25":"0.0089","26":"0.0945","27":"200","28":"2","29":"0","30":"0","31":"27.1940","32":"1","33":"-1.9274","34":"0.3721","35":"0.2676","36":"-0.3327","_rn_":"9"},{"1":"10005","2":"43","3":"68","4":"187","5":"120","6":"80","7":"233","8":"1","9":"25","10":"1","11":"0","12":"0","13":"2861","14":"0","15":"1","16":"1","17":"1","18":"0.7987","19":"1.2565","20":"-0.1144","21":"10.9856","22":"4.7875","23":"5.2311","24":"1.5660","25":"0.0083","26":"0.0913","27":"200","28":"1","29":"2","30":"1","31":"28.4301","32":"0","33":"0.1326","34":"-0.3279","35":"0.3912","36":"-0.1727","_rn_":"10"},{"1":"3284","2":"59","3":"72","4":"206","5":"130","6":"86","7":"181","8":"1","9":"10","10":"1","11":"0","12":"0","13":"2962","14":"0","15":"1","16":"0","17":"0","18":"0.8244","19":"-0.9799","20":"-1.1873","21":"-0.8253","22":"4.8675","23":"5.3279","24":"1.5826","25":"0.0077","26":"0.0877","27":"300","28":"4","29":"1","30":"1","31":"27.9356","32":"1","33":"-0.9074","34":"1.2721","35":"0.3417","36":"0.0273","_rn_":"11"},{"1":"21071","2":"54","3":"67","4":"152","5":"118","6":"76","7":"214","8":"1","9":"0","10":"1","11":"0","12":"0","13":"2885","14":"0","15":"1","16":"1","17":"1","18":"0.9717","19":"0.3558","20":"0.3275","21":"1.0865","22":"4.7707","23":"5.0239","24":"1.5625","25":"0.0085","26":"0.0921","27":"170","28":"3","29":"2","30":"0","31":"23.8040","32":"1","33":"-0.2474","34":"0.7721","35":"-0.0714","36":"-0.2127","_rn_":"12"},{"1":"19069","2":"48","3":"71","4":"156","5":"110","6":"78","7":"280","8":"1","9":"20","10":"1","11":"0","12":"0","13":"3014","14":"0","15":"1","16":"1","17":"1","18":"0.4002","19":"0.8922","20":"-1.8880","21":"0.4726","22":"4.7005","23":"5.0499","24":"1.5477","25":"0.0091","26":"0.0953","27":"170","28":"2","29":"3","30":"1","31":"21.7552","32":"0","33":"1.0726","34":"0.1721","35":"-0.2763","36":"-0.3727","_rn_":"13"},{"1":"12191","2":"39","3":"70","4":"158","5":"110","6":"74","7":"265","8":"1","9":"0","10":"1","11":"1","12":"1","13":"2550","14":"0","15":"1","16":"1","17":"1","18":"0.2155","19":"-0.4919","20":"0.1398","21":"-3.5172","22":"4.7005","23":"5.0626","24":"1.5477","25":"0.0091","26":"0.0953","27":"170","28":"0","29":"3","30":"0","31":"22.6682","32":"0","33":"0.7726","34":"-0.7279","35":"-0.1850","36":"-0.3727","_rn_":"14"},{"1":"10145","2":"49","3":"73","4":"210","5":"118","6":"80","7":"251","8":"1","9":"4","10":"1","11":"0","12":"0","13":"2849","14":"0","15":"1","16":"1","17":"1","18":"0.8796","19":"-0.5020","20":"0.6005","21":"-0.8359","22":"4.7707","23":"5.3471","24":"1.5625","25":"0.0085","26":"0.0921","27":"300","28":"2","29":"3","30":"1","31":"27.7031","32":"0","33":"0.4926","34":"0.2721","35":"0.3185","36":"-0.2127","_rn_":"15"},{"1":"13371","2":"55","3":"72","4":"185","5":"116","6":"76","7":"192","8":"1","9":"0","10":"1","11":"0","12":"0","13":"2982","14":"1","15":"1","16":"1","17":"1","18":"0.8393","19":"-0.4280","20":"-0.1084","21":"-3.9476","22":"4.7536","23":"5.2204","24":"1.5589","25":"0.0086","26":"0.0928","27":"200","28":"3","29":"1","30":"0","31":"25.0878","32":"1","33":"-0.6874","34":"0.8721","35":"0.0569","36":"-0.2527","_rn_":"16"},{"1":"12713","2":"44","3":"60","4":"160","5":"138","6":"82","7":"213","8":"1","9":"0","10":"1","11":"0","12":"0","13":"3120","14":"0","15":"0","16":"0","17":"0","18":"0.4999","19":"-0.5481","20":"0.2706","21":"-2.0253","22":"4.9273","23":"5.0752","24":"1.5948","25":"0.0072","26":"0.0851","27":"170","28":"1","29":"2","30":"0","31":"31.2444","32":"0","33":"-0.2674","34":"-0.2279","35":"0.6726","36":"0.1873","_rn_":"17"},{"1":"21205","2":"56","3":"70","4":"180","5":"114","6":"74","7":"306","8":"1","9":"20","10":"1","11":"0","12":"0","13":"2873","14":"0","15":"1","16":"1","17":"1","18":"0.9806","19":"-0.2022","20":"0.8530","21":"-0.2371","22":"4.7362","23":"5.1930","24":"1.5552","25":"0.0088","26":"0.0937","27":"200","28":"4","29":"3","30":"1","31":"25.8245","32":"1","33":"1.5926","34":"0.9721","35":"0.1306","36":"-0.2927","_rn_":"18"},{"1":"11225","2":"42","3":"68","4":"160","5":"120","6":"72","7":"260","8":"1","9":"0","10":"1","11":"0","12":"0","13":"3018","14":"0","15":"1","16":"1","17":"1","18":"0.1373","19":"-0.1621","20":"-0.2265","21":"-0.7156","22":"4.7875","23":"5.0752","24":"1.5660","25":"0.0083","26":"0.0913","27":"170","28":"1","29":"3","30":"0","31":"24.3253","32":"0","33":"0.6726","34":"-0.4279","35":"-0.0193","36":"-0.1727","_rn_":"19"},{"1":"11249","2":"44","3":"72","4":"180","5":"120","6":"80","7":"181","8":"1","9":"0","10":"1","11":"0","12":"0","13":"1383","14":"0","15":"1","16":"1","17":"1","18":"0.0856","19":"-1.7194","20":"-0.8003","21":"-2.1483","22":"4.7875","23":"5.1930","24":"1.5660","25":"0.0083","26":"0.0913","27":"200","28":"1","29":"1","30":"0","31":"24.4097","32":"0","33":"-0.9074","34":"-0.2279","35":"-0.0109","36":"-0.1727","_rn_":"20"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<pre class="r"><code>wcgs %&gt;% select(chd69, age) %&gt;% str()</code></pre>
<pre><code>## &#39;data.frame&#39;:    3154 obs. of  2 variables:
##  $ chd69: int  0 0 0 0 0 0 0 0 0 0 ...
##  $ age  : int  50 51 59 51 44 47 40 41 50 43 ...</code></pre>
<p>We first look at the effect of smoking (predictor) on CHD (outcome).</p>
<ul>
<li><p><code>smoke</code> is a binary covariate taking values either 0 (<code>non-smoker</code>) or 1 (<code>smoker</code>).</p></li>
<li><p><code>chd69</code> is a binary covariate indicating whether a person developed CHD, 0 for <code>non-developed</code> and 1 for <code>developed.</code></p></li>
</ul>
<p>A <span style="color:#337ab7"><strong>contingency table</strong></span> is an effective method to see the association between two categorical variables. It counts the number of observations in each of the four possible scenarios.
When dealing with just one categorical variable, this is referred to as a <strong>frequency table</strong>, which count the number of observations for each category.</p>
<p>We start out by making a 2x2 contingency table for the development of CHD or not for smokers and nonsmokers:</p>
<pre class="r"><code>contingency_data &lt;- wcgs %&gt;% 
    select(smoke, chd69) %&gt;% 
    mutate(smoke = factor(smoke, levels=c(0,1), labels=c(&quot;non-smoker&quot;,&quot;smoker&quot;)),
           chd69 = factor(chd69, levels=c(0,1), labels=c(&quot;non-developed&quot;, &quot;developed&quot;)))
contingency_table &lt;- with(contingency_data, table(chd69, smoke))
contingency_table</code></pre>
<pre><code>##                smoke
## chd69           non-smoker smoker
##   non-developed       1554   1343
##   developed             98    159</code></pre>
<p>We can display row and column totals if needed.</p>
<pre class="r"><code>contingency_table %&gt;% addmargins()</code></pre>
<pre><code>##                smoke
## chd69           non-smoker smoker  Sum
##   non-developed       1554   1343 2897
##   developed             98    159  257
##   Sum                 1652   1502 3154</code></pre>
<ul>
<li>We see that there are 1502 smokers and that 159 of these developed CHD.</li>
<li>Of the 1652 non-smokers, 98 developed CHD.</li>
</ul>
<p>Visualization of the contingency table</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-6"></span>
<img src="images/stacked_bar.png" alt="Stacked bar plot" width="50%" />
<p class="caption">
Fig. 1: Stacked bar plot
</p>
</div>
<p>The <span style="color:#337ab7">stacked bar graph</span> shows</p>
<ul>
<li>the sample sizes of smokers and non-smokers;</li>
<li>the distribution of developed vs non-developed within each category.</li>
</ul>
<p>The <span style="color:#337ab7">mosaic plot</span> replaces absolute frequencies (counts) with relative frequencies within each category.
It represents each combination of the variables as a rectangle, and the size of the rectangle is proportional to the number of individuals in that combination.</p>
<p>The advantage of mosaic plots is that it demonstrates the difference in estimated conditional probabilities among groups.</p>
<pre class="r"><code>mosaicplot(contingency_table %&gt;% t(), 
           xlab=&quot;Smoke&quot;, ylab=&quot;CHD&quot;, 
           main=&quot;Mosaic plot: Smoke X CHD&quot;, cex.axis = 1.2)</code></pre>
<p><img src="10_Oct_25_LDV_files/figure-html/unnamed-chunk-7-1.png" width="672" style="display: block; margin: auto;" /></p>
<ul>
<li>The widths of the boxes are proportional to the percentage of non-smokers and smokers, respectively. In fact, <span class="math inline">\(52.38\%\)</span> of applicants were non-smokers and <span class="math inline">\(47.62\%\)</span> were smokers.</li>
<li>The heights of the boxes are proportional to percent developed. We can see that non-smokers’ box for the developed on the left is shorter than the smokers’ developed box on the right.
In fact, <span class="math inline">\(5.93\%\)</span> of the non-smokers developed CHD, while <span class="math inline">\(10.59\%\)</span> of the smokers developed CHD. That is, there is a larger proportion of people that developed CHD for smokers compared to non-smokers.</li>
</ul>
<p>We can show the proportions of developing CHD for the two groups (smokers vs. non-smokers) in Table <a href="#tab:risk-table">1</a>.</p>
<pre class="r"><code>risk_table &lt;- contingency_table %&gt;% 
            prop.table(margin=2) %&gt;% 
            as.data.frame.matrix() </code></pre>
<table class="table table-striped table-hover" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:risk-table">Table 1: </span><span id="tab:risk-table">Table 2: </span>Risk of developing CHD for non-smokers and smokers.
</caption>
<thead>
<tr>
<th style="empty-cells: hide;border-bottom:hidden;" colspan="2">
</th>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="2">
<div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Smoke
</div>
</th>
</tr>
<tr>
<th style="text-align:center;">
</th>
<th style="text-align:left;">
</th>
<th style="text-align:center;">
non-smoker
</th>
<th style="text-align:center;">
smoker
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;font-weight: bold;">
CHD
</td>
<td style="text-align:left;font-weight: bold;">
non-developed
</td>
<td style="text-align:center;">
94.07%
</td>
<td style="text-align:center;">
89.41%
</td>
</tr>
<tr>
<td style="text-align:center;font-weight: bold;">
</td>
<td style="text-align:left;font-weight: bold;">
developed
</td>
<td style="text-align:center;">
5.93%
</td>
<td style="text-align:center;">
10.59%
</td>
</tr>
</tbody>
</table>
<ul>
<li>For non-smokers, <span class="math inline">\(5.9\%\)</span> developed CHD.</li>
<li>For smokers, <span class="math inline">\(10.6\%\)</span> developed CHD.</li>
</ul>
<hr />
<div id="measure-or-risk-and-association-for-binary-outcomes" class="section level2">
<h2>Measure or Risk and Association for Binary Outcomes</h2>
<ul>
<li><p>The <em>risk</em> refers to outcome risk for individuals who are smokers or non-smokers and are simply the observed proportions of individuals with CHD in these groups.</p>
<ul>
<li>In our case, the risk for non-smokers (<code>smoke=0</code>, control group) is the proportion who developed CHD among non-smokers, which is <span class="math inline">\(5.9\%\)</span>, denoted as <span class="math inline">\(P(0)\)</span>.</li>
<li>The risk for smokers (<code>smoke=1</code>, treatment group) is the proportion who developed CHD among smokers, which is <span class="math inline">\(10.6\%\)</span>, deonoted as <span class="math inline">\(P(1)\)</span>.</li>
</ul></li>
<li><p>The <span style="color:#008B45FF"><em>risk difference</em></span> or <span style="color:#008B45FF"><em>excess risk</em></span> (ER) is defined as the difference between the estimated risk in the groups defined by the predictor.
<span class="math display">\[
  ER = P(1)- P(0)
  \]</span></p>
<ul>
<li><p>If <span class="math inline">\(ER=0\)</span>, there is no difference in risk between the two groups.</p></li>
<li><p>If <span class="math inline">\(ER&gt;0\)</span>, the risk is higher for the treatment group compared to the control group.</p></li>
<li><p>If <span class="math inline">\(ER&lt;0\)</span>, the risk is lower for the treatment group compared to the control group.</p></li>
</ul>
<p>Because the component risks range between zero and one, the ER can take on values between <span class="math inline">\(-1\)</span> and <span class="math inline">\(1\)</span>, i.e.,
<span class="math display">\[
  -1 &lt; ER &lt; 1
  \]</span></p>
<ul>
<li><p>For our contingency table, we can see that the risk difference is
<span class="math display">\[
  10.6\%-5.9\%=4.7\%
  \]</span></p>
<p>Can be verified as:</p>
<pre class="r"><code>p1 &lt;- risk_table[2,2]
p0 &lt;- risk_table[2,1]
ER &lt;- p1-p0
ER</code></pre>
<pre><code>## [1] 0.04653682</code></pre></li>
</ul></li>
<li><p>The <span style="color:#008B45FF"><em>risk ratio</em></span> or <span style="color:#008B45FF"><em>relative risk</em></span> (RR) is the ratio of these risks.</p>
<p><span class="math display">\[
  RR = \frac{P(1)}{P(0)}
  \]</span></p>
<ul>
<li><p>If <span class="math inline">\(RR=1\)</span>, there is no difference in risk between the two groups.</p></li>
<li><p>If <span class="math inline">\(RR&gt;1\)</span>, the risk is higher for the treatment group compared to the control group.</p></li>
<li><p>If <span class="math inline">\(RR&lt;1\)</span>, the risk is lower for the treatment group compared to the control group.</p></li>
</ul>
<p><span class="math inline">\(RR\)</span> is a relative measure, and can only take nonegative values.</p>
<p><span class="math display">\[
  RR\ge 0
  \]</span></p>
<ul>
<li><p>In our example, the risk ratio is
<span class="math display">\[
  \frac{10.6\%}{5.9\%}=1.8
  \]</span></p>
<p>Can be verified as</p>
<pre class="r"><code>RR &lt;-  p1/p0
RR</code></pre>
<pre><code>## [1] 1.784478</code></pre></li>
</ul></li>
<li><p>The <span style="color:#008B45FF"><strong>odds ratio</strong></span> (OR) is the ratio between the corresponding odds in the two groups.</p>
<ul>
<li><p>The <span style="color:#008B45FF"><strong>odds</strong></span> of an outcome occurring are computed as the probability of <em>occurrence</em> divided by the complementary probability that the event does <em>not occur</em>.</p>
<p>Given a probability <span class="math inline">\(p\)</span>, the odds is given by</p>
<p><span class="math display">\[
  \text{odds} = \frac{p}{1-p}
  \]</span></p>
<p>Since the denominators of these two probabilities are identical, the odds can be also be calculated as the ratio of the number of outcomes to nonoutcomes.</p>
<p>For example, getting heads with a fair coin has <em>even odds</em>, that is, the probability of getting a head is <span class="math inline">\(50\%\)</span>.</p></li>
<li><p>The odds of CHD occurrence in the smokers groups are
<span class="math display" id="eq:odds1">\[
  \begin{align}\tag{1}
  \text{odds}(smoke=1) = \frac{P(1)}{1-P(1)} = \frac{10.6\%}{1-10.6\%} = 11.84\%
  \end{align}
  \]</span></p>
<p>Can be verified as</p>
<pre class="r"><code>p1/(1-p1)</code></pre>
<pre><code>## [1] 0.1183917</code></pre></li>
<li><p>The odds of CHD occurrence in the non-smokers groups are
<span class="math display" id="eq:odds0">\[
  \begin{align}\tag{2}
  \text{odds}(smoke=0) = \frac{P(0)}{1-P(0)} = \frac{5.9\%}{1-5.9\%} = 6.31\%
  \end{align}
  \]</span></p>
<p>Can be verified as</p>
<pre class="r"><code>p0/(1-p0)</code></pre>
<pre><code>## [1] 0.06306306</code></pre></li>
<li><p>The odds ratio is the ratio between the corresponding odds in the two groups.</p>
<p><span class="math display">\[
  OR = \frac{P(1)/[1-P(1)]}{P(0)/[1-P(0)]}
  \]</span></p>
<ul>
<li>If <span class="math inline">\(OR=1\)</span>, the treatment does not affect odds of outcome.</li>
<li>If <span class="math inline">\(OR&gt;1\)</span>, the treatment groups has higher odds of outcome.</li>
<li>If <span class="math inline">\(OR&lt;1\)</span>, the treatment groups has lower odds of outcome.</li>
</ul>
<p><span class="math inline">\(OR\)</span> is nonnegative.</p>
<p><span class="math display">\[
  OR&gt;0
  \]</span></p></li>
<li><p>In our contingency table, the odds ratio is given by</p>
<p><span class="math display">\[
  \frac{11.84\%}{6.31\%} = 1.88
  \]</span></p>
<p>Can be verified as</p>
<pre class="r"><code>OR &lt;- (p1/(1-p1))/(p0/(1-p0))
OR</code></pre>
<pre><code>## [1] 1.877353</code></pre></li>
</ul></li>
</ul>
<hr />
<p>From a fitted logistic model we may estimate the odds ratio corresponding to a one unit’s increase in a covariate. Use this result to compute the odds ratio for CHD for a smoker compared to a non-smoker.</p>
</div>
<div id="logistic-regression-with-a-single-predictor" class="section level2">
<h2>Logistic Regression with a Single Predictor</h2>
<p>We then use a logistic regression model with smoke as covariate.</p>
<p>Mathematical representation:
<span class="math display" id="eq:ex1">\[
\begin{align} \tag{3}
p(x) = P(y=1\vert x) = \frac{\exp(\beta_0+\beta_1 x)}{1+\exp(\beta_0+\beta_1 x)}
\end{align}
\]</span></p>
<p>We need to reformulate Eq. <a href="#eq:ex1">(3)</a> for the interpretation so that only the linear term is on the right side of the equation.</p>
<p><span class="math display" id="eq:ex1-log">\[
\begin{align} \tag{4}
\log \left[\frac{p(x)}{1-p(x)} \right] = \beta_0+\beta_1 x \,.
\end{align}
\]</span></p>
<p>The expression on the LHS is called the log odds.</p>
<p>Taking the exponential to Eq. <a href="#eq:ex1-log">(4)</a>, we obtain:
<span class="math display">\[
\begin{align}
\frac{p(x)}{1-p(x)} = \exp (\beta_0+\beta_1 x) \,.
\end{align}
\]</span></p>
<p>Note that the LHS is actually the odds.</p>
<p>In logistic regression, if we take <span style="color:#337ab7">the exponential of the coefficient</span>, it is the <span style="color:#337ab7"><strong>odds ratio corresponding to one unit’s increase in the value of the covariate</strong></span>, holding other variables constant.</p>
<pre class="r"><code>fit.smoke &lt;- glm(chd69~smoke, data=wcgs, family=binomial)
summary(fit.smoke)</code></pre>
<pre><code>## 
## Call:
## glm(formula = chd69 ~ smoke, family = binomial, data = wcgs)
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)  -2.7636     0.1042  -26.54  &lt; 2e-16 ***
## smoke         0.6299     0.1337    4.71 2.47e-06 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 1781.2  on 3153  degrees of freedom
## Residual deviance: 1758.4  on 3152  degrees of freedom
## AIC: 1762.4
## 
## Number of Fisher Scoring iterations: 5</code></pre>
<p>The regression result can be summarized in Table <a href="#tab:fit-smoke">3</a>.</p>
<table style="text-align:center">
<caption>
<strong><span id="tab:fit-smoke"><span id="tab:fit-smoke">Table 3: </span></span>Logistic regression of CHD on smoke.</strong>
</caption>
<tr>
<td colspan="2" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
<em>Dependent variable:</em>
</td>
</tr>
<tr>
<td>
</td>
<td colspan="1" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
chd69
</td>
</tr>
<tr>
<td colspan="2" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
smoke
</td>
<td>
0.6299<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.1337)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
Constant
</td>
<td>
-2.7636<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.1042)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
</tr>
<tr>
<td colspan="2" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
Observations
</td>
<td>
3,154
</td>
</tr>
<tr>
<td style="text-align:left">
Log Likelihood
</td>
<td>
-879.1905
</td>
</tr>
<tr>
<td style="text-align:left">
Akaike Inf. Crit.
</td>
<td>
1,762.3810
</td>
</tr>
<tr>
<td colspan="2" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
<em>Note:</em>
</td>
<td style="text-align:right">
<span>*</span>: p&lt;0.1; <span>**</span>: <strong>p&lt;0.05</strong>; <span>***</span>: p&lt;0.01 <br> Standard errors in parentheses.
</td>
</tr>
</table>
<p>In this case, <span style="color:#337ab7">the odds ratio for CHD for a smoker compared to a non-smoker</span> can be obtained by</p>
<p><span class="math display">\[
e^{0.63} = 1.88\, ,
\]</span>
which is exactly the same number as we calculated using the contingency table.</p>
<p>More interpretations: the odds ratio being <span class="math inline">\(1.88\)</span> means that <span style="color:#337ab7">the odds of a smoker developing CHD are <span class="math inline">\(1.88\)</span> times greater than the odds of a non-smoker developing CHD</span>.</p>
<p>More formally, if you increase the value of covariate <span class="math inline">\(x_1\)</span> by one unit, the <span style="color:#337ab7">estimated odds change by a factor of <span class="math inline">\(\exp(\beta_1)\)</span></span>.</p>
<p>We know that the odds for non-smokers are <span class="math inline">\(6.31\%\)</span> from Eq. <a href="#eq:odds0">(2)</a>. Given the odds ratio of <span class="math inline">\(1.88\)</span>, this indicates that the <strong>expected</strong> odds for smokers to develop CHD is
<span class="math display">\[
\begin{aligned}
\text{odds}\,(smoker=1) &amp;=  \text{odds}\,(smoker=0) \times \text{odds ratio}  \\
&amp;=6.3\% \times 1.88  \\
&amp;= 11.84
\end{aligned}
\]</span>
This can be verified as</p>
<pre class="r"><code># odds(smoker=0) * exp(beta1)
p0/(1-p0) * exp(fit.smoke$coefficients[2]) </code></pre>
<pre><code>##     smoke 
## 0.1183917</code></pre>
<p><strong>Interpretation of intercept</strong>: The exponential of <span class="math inline">\(\beta_0\)</span> is the estimated odds when the categorical covariates are at the reference level and all numerical covariates are zero.</p>
<p>In our case, the estimated odds for a non-smoker to develop CHD is
<span class="math display">\[
\text{odds}\,(smoker=0) = e^{-2.764} = 6.3\%
\]</span></p>
<hr />
<p>We now consider a numerical predictor, <code>age</code>.
We then use logistic regression to study the effect of age for the risk of developing CHD:</p>
<pre class="r"><code>fit.age &lt;-  glm(chd69~age, data=wcgs, family=binomial)
summary(fit.age)</code></pre>
<pre><code>## 
## Call:
## glm(formula = chd69 ~ age, family = binomial, data = wcgs)
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept) -5.93952    0.54932 -10.813  &lt; 2e-16 ***
## age          0.07442    0.01130   6.585 4.56e-11 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 1781.2  on 3153  degrees of freedom
## Residual deviance: 1738.4  on 3152  degrees of freedom
## AIC: 1742.4
## 
## Number of Fisher Scoring iterations: 5</code></pre>
<p>The regression result can be summarized in Table <a href="#tab:fit-age">4</a>.</p>
<table style="text-align:center">
<caption>
<strong><span id="tab:fit-age"><span id="tab:fit-age">Table 4: </span></span>Logistic regression of CHD on age.</strong>
</caption>
<tr>
<td colspan="2" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
<em>Dependent variable:</em>
</td>
</tr>
<tr>
<td>
</td>
<td colspan="1" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
chd69
</td>
</tr>
<tr>
<td colspan="2" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
age
</td>
<td>
0.0744<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.0113)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
Constant
</td>
<td>
-5.9395<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.5493)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
</tr>
<tr>
<td colspan="2" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
Observations
</td>
<td>
3,154
</td>
</tr>
<tr>
<td style="text-align:left">
Log Likelihood
</td>
<td>
-869.1781
</td>
</tr>
<tr>
<td style="text-align:left">
Akaike Inf. Crit.
</td>
<td>
1,742.3560
</td>
</tr>
<tr>
<td colspan="2" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
<em>Note:</em>
</td>
<td style="text-align:right">
<span>*</span>: p&lt;0.1; <span>**</span>: <strong>p&lt;0.05</strong>; <span>***</span>: p&lt;0.01 <br> Standard errors in parentheses.
</td>
</tr>
</table>
<p> </p>
<ul>
<li>The odds ratio for one year increase in age is <span class="math inline">\(e^{0.0744} = 1.077\, .\)</span> This means that for each additional year of age, the odds increase by a factor of <span class="math inline">\(1.077.\)</span></li>
<li>The odds ratio for a ten-year increase is <span class="math inline">\(e^{0.0744\times 10} = 2.10\, .\)</span> That is, the odds are <span class="math inline">\(2.10\)</span> times higher for an additional ten years of age.</li>
</ul>
<p>Can be verified using the following codes.</p>
<pre class="r"><code>expcoef &lt;- function(glmobj){
    # computing odds ratio with 95% confidence limits
    regtab &lt;- summary(glmobj)$coef 
    expcoef &lt;- exp(regtab[,1]) 
    lower &lt;- expcoef * exp(-1.96*regtab[,2]) 
    upper &lt;- expcoef * exp(1.96*regtab[,2]) 
    return (cbind(expcoef,lower, upper))
} </code></pre>
<p>Table <a href="#tab:OR-age">5</a> shows the odds ratio for age and its <span class="math inline">\(95\%\)</span> confidence interval.</p>
<pre class="r"><code>expcoef(fit.age)[-1,,drop=FALSE] %&gt;% 
    kable(digits = 4, escape= TRUE, 
          caption = &quot;Exponential of the coefficient and 95% CI.&quot;) %&gt;% 
    kable_styling(full_width = FALSE)</code></pre>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:OR-age">Table 5: </span><span id="tab:OR-age">Table 6: </span>Exponential of the coefficient and 95% CI.
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
expcoef
</th>
<th style="text-align:right;">
lower
</th>
<th style="text-align:right;">
upper
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
age
</td>
<td style="text-align:right;">
1.0773
</td>
<td style="text-align:right;">
1.0537
</td>
<td style="text-align:right;">
1.1014
</td>
</tr>
</tbody>
</table>
<hr />
</div>
<div id="logistic-regression-with-several-predictors" class="section level2">
<h2>Logistic Regression with Several Predictors</h2>
<p>Consider the WCGS study with CHD as outcome and age, cholesterol (mg/dL), systolic blood pressure (mmHg), body mass index (kg/m2), and smoking (0/1) as predictors.</p>
<p>Mathematical representation:
<span class="math display" id="eq:ex-multi">\[
\begin{align}
p(\boldsymbol x) = P(y=1\vert \boldsymbol x) = \frac{\exp(\beta_0+\beta_1 x_2 + \cdots +\beta_K x_K)}{1+\exp(\beta_0+\beta_1 x_2+ \cdots +\beta_K x_K)}
\end{align} \tag{5}
\]</span>
The odds given <span class="math inline">\(\boldsymbol{x}=[1, x_2, \ldots, x_K]^T\)</span> can be obtained by:
<span class="math display">\[
\log \left[\frac{p(\boldsymbol x)}{1-p(\boldsymbol x)}\right] = \beta_0+\beta_1 x_x + \cdots +\beta_K x_K
\]</span></p>
<pre class="r"><code>wcgs.mult &lt;- glm(chd69~age+chol+sbp+bmi+smoke, data=wcgs, family=binomial, subset=(chol&lt;600))</code></pre>
<table style="text-align:center">
<caption>
<strong><span id="tab:fit-mult"><span id="tab:fit-mult">Table 7: </span></span>Logistic regression of CHD on multiple covariates.</strong>
</caption>
<tr>
<td colspan="2" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
<em>Dependent variable:</em>
</td>
</tr>
<tr>
<td>
</td>
<td colspan="1" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
chd69
</td>
</tr>
<tr>
<td colspan="2" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
age
</td>
<td>
0.0644<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.0119)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
chol
</td>
<td>
0.0107<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.0015)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
sbp
</td>
<td>
0.0193<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.0041)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
bmi
</td>
<td>
0.0574<sup>**</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.0264)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
smoke
</td>
<td>
0.6345<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.1402)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
Constant
</td>
<td>
-12.3110<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.9773)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
</tr>
<tr>
<td colspan="2" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
Observations
</td>
<td>
3,141
</td>
</tr>
<tr>
<td style="text-align:left">
Log Likelihood
</td>
<td>
-807.1925
</td>
</tr>
<tr>
<td style="text-align:left">
Akaike Inf. Crit.
</td>
<td>
1,626.3850
</td>
</tr>
<tr>
<td colspan="2" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
<em>Note:</em>
</td>
<td style="text-align:right">
<span>*</span>: p&lt;0.1; <span>**</span>: <strong>p&lt;0.05</strong>; <span>***</span>: p&lt;0.01 <br> Standard errors in parentheses.
</td>
</tr>
</table>
<p>The coefficient (<span class="math inline">\(0.635\)</span>) for the binary predictor variable <code>smoke</code> is the log odds ratio comparing smokers to nonsmokers for fixed values of <code>age</code>, <code>chol</code>, <code>sbp</code>, and <code>bmi</code>. The corresponding odds ratio
<span class="math display">\[
\exp(0.635) = 1.89
\]</span>
measures the proportionate increase in the odds of developing CHD for smokers compared to nonsmokers <em>adjusted for age, cholesterol, SBP, and BMI</em>.</p>
Table <a href="#tab:log-mult">8</a> shows ddds ratios corresponding to all covariates and their confidence intervals.
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:log-mult">Table 8: </span><span id="tab:log-mult">Table 9: </span>Odds ratios with confidence intervals.
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
expcoef
</th>
<th style="text-align:right;">
lower
</th>
<th style="text-align:right;">
upper
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
age
</td>
<td style="text-align:right;">
1.0666
</td>
<td style="text-align:right;">
1.0420
</td>
<td style="text-align:right;">
1.0918
</td>
</tr>
<tr>
<td style="text-align:left;">
chol
</td>
<td style="text-align:right;">
1.0108
</td>
<td style="text-align:right;">
1.0078
</td>
<td style="text-align:right;">
1.0138
</td>
</tr>
<tr>
<td style="text-align:left;">
sbp
</td>
<td style="text-align:right;">
1.0195
</td>
<td style="text-align:right;">
1.0113
</td>
<td style="text-align:right;">
1.0277
</td>
</tr>
<tr>
<td style="text-align:left;">
bmi
</td>
<td style="text-align:right;">
1.0591
</td>
<td style="text-align:right;">
1.0058
</td>
<td style="text-align:right;">
1.1153
</td>
</tr>
<tr>
<td style="text-align:left;">
smoke
</td>
<td style="text-align:right;">
1.8860
</td>
<td style="text-align:right;">
1.4329
</td>
<td style="text-align:right;">
2.4824
</td>
</tr>
</tbody>
</table>
<hr />
</div>
</div>
<div id="logistic-regression-model-representation" class="section level1">
<h1>Logistic Regression Model Representation</h1>
<p>We have <span class="math inline">\(n\)</span> observations <span class="math inline">\((x_1, y_1), (x_2, y_2), \ldots, (x_n, y_n)\)</span>.</p>
<p>Here <span class="math inline">\(y_i\)</span> is a binary outcome variable for observation <span class="math inline">\(i\)</span> and takes values 0 or 1, and <span class="math inline">\(x_i\)</span> is a predictor.</p>
<p>We want to model the probability of <span class="math inline">\(y_i=1\)</span> (observing a one) conditional on some predictors <span class="math inline">\(x_i\)</span>:</p>
<p><span class="math display" id="eq:linear-probability-model">\[
\begin{equation} \tag{6}
P\,(y_i=1 | x_i) = x_i&#39;\beta .
\end{equation}
\]</span>
We call Eq. <a href="#eq:linear-probability-model">(6)</a> as the <span style="color:#008B45FF">Linear Probability Model</span>.</p>
<p>Note that <span class="math inline">\(\mathbb{E}(y_i\vert x_i) = P\,(y_i=1 | x_i)\)</span>. That is, the conditional expectation of <span class="math inline">\(y_i\)</span> is the probability of observing a one given <span class="math inline">\(x_i\,.\)</span></p>
<p>Proof:</p>
<p><span class="math display">\[
\begin{aligned}
\mathbb{E}(y_i|x_i)  
&amp;= \sum_{y_i\in \mathcal Y} y_i\, P\,(y=y_i|x_i) \\
&amp;= 1 \times P\,(y_i=1|x_i) + 0 \times P\,(y_i=0|x_i) \\
&amp;= P\,(y_i=1|x_i)
\end{aligned}
\]</span>
where <span class="math inline">\(\mathcal Y = \{0, 1\}\)</span> is the sample space of <span class="math inline">\(y_i\)</span>.</p>
<p>We can estimate <span class="math inline">\(\beta\)</span> in Eq. <a href="#eq:linear-probability-model">(6)</a> by OLS.</p>
<p><strong>Issue</strong>: Will have <span class="math inline">\(x&#39;\beta\)</span> outside of <span class="math inline">\([0,1]\)</span> for some values of <span class="math inline">\(x\)</span>.</p>
<p>Alternative approach: let <span class="math inline">\(F(·)\)</span> be a known cdf and specify</p>
<p><span class="math display">\[
P\,(y_i=1|x_i) = F(x_i&#39;\beta) \,.
\]</span></p>
<ul>
<li>When <span class="math inline">\(\displaystyle F(u)= \frac{1}{1+e^{-u}}\)</span> (the logistic cdf), where <span class="math inline">\(u=x&#39;\beta\)</span>, this is called the <span style="color:#008B45FF">logit model</span>.</li>
<li>When <span class="math inline">\(\displaystyle F(u)= \Phi(u)\)</span> (the standard normal cdf), this is called the <span style="color:#008B45FF">probit model</span>.</li>
</ul>
<p>Plug in <span class="math inline">\(u=x&#39;\beta\)</span> and the logistic cdf, we can express the general logistic model as:</p>
<p><span class="math display" id="eq:logit-model2" id="eq:logit-model1" id="eq:logit-model0">\[
\begin{align}
p(x) &amp;= \frac{1}{1+e^{-u}}  \tag{7} \\
&amp;= \frac{1}{1+e^{-x&#39;\beta}} \tag{8} \\
&amp;= \frac{e^{x&#39;\beta}}{1+e^{x&#39;\beta}}  \tag{9} \\
\end{align}
\]</span></p>
<p>On the left hand side, <span class="math inline">\(p(x)=P(y=1\vert x)\)</span> is a probability function that we observe a one (<span class="math inline">\(y=1\)</span> is the outcome) conditional on <span class="math inline">\(x\)</span> (predictors).</p>
<p>Eq. <a href="#eq:logit-model1">(8)</a> gives a “S-shaped” relationship between <span class="math inline">\(p(x)\)</span> and <span class="math inline">\(x&#39;\beta\)</span> and ensures that <span class="math inline">\(p(x)\)</span> stays between 0 and 1.
See Fig. <a href="#fig:logit-regression">2</a>. No matter the value of <span class="math inline">\(u\)</span>, <span class="math inline">\(p\)</span> remains bounded between 0 and 1.</p>
<pre class="r"><code>u &lt;- seq(-4, 4, length.out = 100)
p &lt;- 1/(1 + exp(-u))
plot(u, p, type = &quot;l&quot;, ylab=&quot;F(u)&quot;)</code></pre>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:logit-regression"></span>
<img src="10_Oct_25_LDV_files/figure-html/logit-regression-1.png" alt="Logistic regression cdf" width="80%" />
<p class="caption">
Fig. 2: Logistic regression cdf
</p>
</div>
<ul>
<li>If <span class="math inline">\(\mu=x&#39;\beta=0\)</span>, then <span class="math inline">\(p(x)=0.5\)</span>, there is an equal probability whether the outcome event will occur or not.</li>
<li>If <span class="math inline">\(\mu=x&#39;\beta&gt;0\)</span>, then <span class="math inline">\(p(x)&gt;0.5\)</span>, there is a larger probability that the outcome event will occur.
<ul>
<li>In this case, we could predict <span class="math inline">\(E[y\vert x]=1\)</span>.</li>
</ul></li>
<li>If <span class="math inline">\(\mu=x&#39;\beta&lt;0\)</span>, then <span class="math inline">\(p(x)&lt;0.5\)</span>, there is a smaller probability that the outcome event will occur.
<ul>
<li>In this case, we could predict <span class="math inline">\(E[y\vert x]=0\)</span>.</li>
</ul></li>
<li>Note that it is <em>not</em> necessary to divide at <span class="math inline">\(0.5\)</span>. Different threshold values could be used depending on the application in question.</li>
</ul>
<p>Eq. <a href="#eq:logit-model1">(8)</a> can be written as:</p>
<p><span class="math display" id="eq:logit-odds">\[
\begin{equation} \tag{10}
\frac{p(x)}{1-p(x)} = \exp{(x&#39;\beta)}
\end{equation}
\]</span></p>
<p>We use an example of a single predictor with an intercept to demonstrate the <strong>interpretation</strong> of the regression coefficient <span class="math inline">\(\beta\)</span>.</p>
<p>If we consider two observations with covariate values <span class="math inline">\(x\)</span> and <span class="math inline">\(x+\Delta x\)</span>, respectively.</p>
<p>The odds given <span class="math inline">\(x\)</span> can be obtained by:
<span class="math display">\[
\text{odds}(x) = \frac{P(y=1\vert x)}{1- P(y=1\vert x)} = \exp(\beta_0 + \beta_1 x) \,.
\]</span>
The odds given <span class="math inline">\((x+\Delta x)\)</span> are
<span class="math display">\[
\text{odds}(x+\Delta x) = \frac{P(y=1\vert x+\Delta x)}{1- P(y=1\vert x+\Delta x)} = \exp\left(\beta_0 + \beta_1 (x+\Delta x)\right)  \,.
\]</span></p>
<p>Their odds ratio becomes
<span class="math display">\[
\begin{aligned}
\frac{\text{odds}(x+\Delta x)}{\text{odds}(x)}
&amp;= \frac{p(x+\Delta x)/[1-p(x+\Delta x)]}{p(x)/[1-p(x)}  \\
&amp;= \frac{\exp{\left(\beta_0 + \beta_1 (x+\Delta x)\right)}}{\exp{\left(\beta_0 + \beta_1 x\right)}} \\
&amp;= \exp{(\beta_1\Delta x)} \,.
\end{aligned}
\]</span>
In particular, <span class="math inline">\(e^{\beta_1}\)</span> is the <span style="color:#337ab7">odds ratio corresponding to one unit’s increase in the value of the covariate</span>.</p>
<p>Suppose <span class="math inline">\(x\)</span> is binary (smoker vs. non-smoker), then
<span class="math display">\[
\frac{\text{odds}(x=1)}{\text{odds}(x=0)} = \exp (\beta_1).
\]</span></p>
<p>In other words, the exponential of the regression coefficient <span class="math inline">\((e^{\beta_1})\)</span> is the odds ratio for the odds given the treatment (smokers) to the odds in absence of the treatment (non-smokers).</p>
<p>In our case, the odds ratio for CHD for a smoker compared to a non-smoker based on the logistic regression in Table <a href="#tab:fit-smoke">3</a> is
<span class="math display">\[
\frac{\text{odds}(smoke=1)}{\text{odds}(smoke=0)} = \exp (0.63) = 1.88 \,.
\]</span></p>
<p>Suppose <span class="math inline">\(x\)</span> is numerical (e.g., age), then the interpretation would be changing <span class="math inline">\(x\)</span> by one unit would lead to the odds change by a factor of <span class="math inline">\(\exp (\beta).\)</span></p>
<ul>
<li><span class="math inline">\(\beta&gt;0 \Rightarrow OR=\exp(\beta)&gt;1\)</span>, indicating one unit change in <span class="math inline">\(x\)</span> would make the event more likely to happen.</li>
<li><span class="math inline">\(\beta&lt;0 \Rightarrow OR=\exp(\beta)&lt;1\)</span>, indicating one unit change in <span class="math inline">\(x\)</span> would make the event less likely to happen.</li>
<li><span class="math inline">\(\beta=0 \Rightarrow OR=\exp(\beta)=1\)</span>, indicating there is a <span class="math inline">\(50/50\)</span> chance that the event will occur given one unit change in <span class="math inline">\(x\)</span>.</li>
</ul>
<p>The same interpretations apply to logistic regressions with several indicators too, except that you have to add an additional comment — <em>holding all other variables constant</em>.</p>
<p>By Eq. <a href="#eq:logit-odds">(10)</a>, the logistic regression model may also be given as:</p>
<p><span class="math display">\[
\log \left[\frac{p(x)}{1-p(x)} \right] = x&#39;\beta \,.
\]</span>
Thus the logistic regression model is linear in the log-odds.</p>
<hr />
<div id="confidence-intervals-for-beta-and-odds-ratio" class="section level2">
<h2>Confidence intervals for <span class="math inline">\(\beta\)</span> and odds ratio</h2>
<p>A <span class="math inline">\(95\%\)</span> confidence interval for <span class="math inline">\(\beta_j\)</span>, <span class="math inline">\(j=1,\ldots,K,\)</span> (based on the normal approximation) is given by:
<span class="math display">\[
[\widehat{L}, \widehat{U}] = [\hat{\beta}_j - 1.96\cdot se(\hat{\beta}_j),\, \hat{\beta}_j + 1.96\cdot se(\hat{\beta}_j)]
\]</span>
The odds ratio:
<span class="math display">\[
OR = \exp (\hat{\beta}_j)
\]</span>
We obtain the <span class="math inline">\(95\%\)</span> confidence interval for OR by taking the exponential of the lower and upper limits of the confidence interval for <span class="math inline">\(\beta_j\)</span>
<span class="math display">\[
[\exp(\widehat{L}),\, \exp(\widehat{U})] \,.
\]</span></p>
<p>Using the regression result in Table <a href="#tab:fit-age">4</a>, we have <span class="math inline">\(\hat{\beta}_1= 0.0744\)</span> and <span class="math inline">\(se(\hat{\beta}_1)=0.0113\)</span>. Hence, the <span class="math inline">\(95\%\)</span> CI for <span class="math inline">\(\beta_1\)</span>:
<span class="math display">\[
[0.0744-1.96\times 0.0113, \, 0.0744+1.96\times 0.0113] = [0.0523, \, 0.0965] \,.
\]</span>
The estimate of odds ratio:
<span class="math display">\[
OR = e^{0.0744} = 1.077
\]</span>
The <span class="math inline">\(95\%\)</span> confidence interval for OR :
<span class="math display">\[
[\exp(0.0523), \, \exp(0.0965)] = [1.0537, 1.1013]
\]</span></p>
<p>Note that odds ratios for continuous independent variables tend to be close to one, this does NOT suggest that the coefficients are insignificant. Use the <em>t</em>-test for statistical significance.</p>
<p><span style="color:#008B45FF">T-test</span> for <span class="math inline">\(\beta_j=0\)</span>.</p>
<p><span class="math display">\[
\begin{aligned}
&amp;\text{H}_0: \beta_j=0  \\
&amp;\text{H}_1: \beta_j\ne0
\end{aligned}
\]</span></p>
<p>We use the following statistic
<span class="math display">\[
z = \frac{\hat{\beta}_j-\beta_j}{se_{\hat{\beta}_j}}  \sim N(0,1) \,,
\]</span>
which follows a standard normal distribution.</p>
<p>The <em>z</em>-value can be calculated as
<span class="math display">\[
z = \frac{0.0744}{0.0113} = 6.58
\]</span>
which is larger than the critical value at <span class="math inline">\(5\%\)</span> significance level
<span class="math display">\[
c_{.025} = \Phi^{-1}(1-.025) = 1.96 \,.
\]</span></p>
<p>We conclude that <span class="math inline">\(\beta_1\)</span> is highly significant. That is, an increase in age significantly raises the odds for developing CHD.</p>
<hr />
</div>
<div id="estimation-by-maximum-likelihood" class="section level2">
<h2>Estimation by Maximum Likelihood</h2>
<p>If we condition on the <span class="math inline">\(x_i\)</span>’s, the distribution of <span class="math inline">\(y_i\)</span> given <span class="math inline">\(x_i\)</span> is <span class="math inline">\(\text{Bernoulli}\,(p(x))\)</span>, where <span class="math inline">\(p(x)=F(x&#39;\beta)\)</span>.</p>
<p>Conditional density is</p>
<p><span class="math display">\[
\begin{aligned}
f\,(y_i | x_i ) &amp;= \begin{cases}
F(x&#39;\beta) &amp; \text{if $y_i=1$} \\
1- F(x&#39;\beta) &amp; \text{if $y_i=0$} \\
\end{cases} \\
&amp;= F(x&#39;\beta)^{y_i} \left[1- F(x&#39;\beta)\right]^{1-y_i} \,.
\end{aligned}
\]</span></p>
<p>This gives the log likelihood</p>
<p><span class="math display">\[
\begin{align*}
\log L(\beta) &amp;= \sum_{i=1}^n \log f\,(y_i | x_i ) \\
&amp;= \sum_{i=1}^n \log \left\{F(x&#39;\beta)^{y_i} \left[1- F(x&#39;\beta)\right]^{1-y_i} \right\} \\
&amp;= \sum_{i=1}^n \left\{y_i \log F(x&#39;\beta) + {1-y_i} \log \left[1- F(x&#39;\beta)\right] \right\} \\
&amp;= \sum_{y_i=1} \log  F(x&#39;\beta) + \sum_{y_i=0} \log \left[1- F(x&#39;\beta)\right] \,.
\end{align*}
\]</span></p>
<p><span class="math inline">\(\hat{\beta}_{ML}\)</span> maximizes <span class="math inline">\(\log L(\beta)\)</span>.</p>
</div>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3,h4",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS_CHTML.js";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
